exclude: |
  (?x)^(
    ^\.venv/.*$
    | ^env/.*$
    | ^venv/.*$
    | ^__pycache__/.*$
    | ^static/.*$
    | ^media/.*$
    | ^migrations/.*$
    | ^node_modules/.*$
    | ^build/.*$
    | ^dist/.*$
    | ^\.git/.*$
    | ^frontend/.*$
  )$

repos:
  # -------------------------------
  # üëç B√°sicos e essenciais
  # -------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # -----------------------------------
  # üêç Ruff (lint + fix + import sorting)
  # -----------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff
        args: ["--fix"]

  # -------------------------
  # üñ§ Black (formata√ß√£o)
  # -------------------------
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  # -------------------------
  # üßπ PyUpgrade (melhores pr√°ticas modernas)
  # -------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]

  # -------------------------
  # ‚ùó Typos (corrige errors de digita√ß√£o)
  # -------------------------
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos

  # -------------------------
  # üß© Commitizen (valida√ß√£o extra + commit guiado opcional)
  # -------------------------
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
      - id: commitizen
        name: "commitizen check"
        stages: [commit-msg]

  # -------------------------
  # üß™ Rodar testes antes do push
  # -------------------------
  - repo: local
    hooks:
      - id: run-tests
        name: Run Django Tests before push
        entry: make run-tests
        language: system
        pass_filenames: false
        stages: [pre-push]
